### PR TITLE
uses the latest Rifampicin and Digoxin models

### PR DESCRIPTION
**Pull request by TWendl**

### CODE REVIEW

**Comment by Yuri05** [comment]
Waiting with the review until https://github.com/Open-Systems-Pharmacology/Rifampicin-Model/pull/14#discussion_r1743608586 and https://github.com/Open-Systems-Pharmacology/Digoxin-Model/issues/12 are fixed (which probably will also require modifications of this snapshot)

**Comment by Yuri05** [comment]
@TWendl It seems that the observer building block **Fold-change in concentration** is not used in any simulation.
Is it OK?
grafik

**Comment by Yuri05** [comment]
@TWendl No observed data in these 2 simulations. Is it OK?
grafik

**Comment by TWendl** [comment]
> @TWendl No observed data in these 2 simulations. Is it OK? grafik

Correct! No c-t profiles available, just AUCR and CmaxR could be extracted!

**Comment by TWendl** [comment]
> @TWendl It seems that the observer building block **Fold-change in concentration** is not used in any simulation. Is it OK? grafik

I think we can delete it! To my knowledge, this observer was meant for other purposes!

**Comment by Yuri05** [comment]
> > @TWendl It seems that the observer building block **Fold-change in concentration** is not used in any simulation. Is it OK? grafik
> 
> I think we can delete it! To my knowledge, this observer was meant for other purposes!

OK, merging it now. Will create a separate issue for the observer.

**Review by Yuri05 — APPROVED** [review]

**Pull request merged**
